import { AppState } from "./types";

export function buildSeedState(): AppState {
  return {
    role: "ADMIN",
    patients: [
      { id: "p-aisha", name: "Aisha Rahman", age: 34, phone: "+971 50 214 8890", assignedDoctor: "Dr. Layla Haddad", status: "Stable" },
      { id: "p-omar", name: "Omar Al Mansoori", age: 52, phone: "+971 55 681 2243", assignedDoctor: "Dr. Layla Haddad", status: "Needs nurse review" },
      { id: "p-fatima", name: "Fatima Al Zaabi", age: 61, phone: "+971 52 903 4471", assignedDoctor: "Dr. Omar Sheikh", status: "Stable" },
      { id: "p-khalid", name: "Khalid Nasser", age: 45, phone: "+971 56 110 7825", assignedDoctor: "Dr. Omar Sheikh", status: "Doctor review" },
      { id: "p-mariam", name: "Mariam Al Suwaidi", age: 29, phone: "+971 50 377 9014", assignedDoctor: "Dr. Layla Haddad", status: "Completed" },
      { id: "p-yusuf", name: "Yusuf Hamdan", age: 58, phone: "+971 54 220 6638", assignedDoctor: "Dr. Omar Sheikh", status: "Needs nurse review" },
      { id: "p-reem", name: "Reem Al Qasimi", age: 47, phone: "+971 55 842 1390", assignedDoctor: "Dr. Layla Haddad", status: "Stable" },
    ],
    visits: [
      {
        id: "v-aisha-1",
        patientId: "p-aisha",
        date: "10 Jun 2025",
        diagnosis: "Minor outpatient procedure (cyst removal, forearm)",
        treatment: "Local excision, sterile dressing, oral analgesia",
        notes: "Procedure uneventful. Advised wound care and rest. Post-procedure follow-up protocol started.",
      },
      {
        id: "v-omar-1",
        patientId: "p-omar",
        date: "8 Jun 2025",
        diagnosis: "Acute upper respiratory infection",
        treatment: "Amoxicillin 500mg TID x 7 days, fluids, rest",
        notes: "Mild fever on presentation. Acute infection follow-up protocol started.",
      },
      {
        id: "v-fatima-1",
        patientId: "p-fatima",
        date: "2 Jun 2025",
        diagnosis: "Hypertension, type 2 diabetes",
        treatment: "Amlodipine 5mg OD, Metformin 500mg BID",
        notes: "BP and HbA1c stable. Chronic condition monitoring continues.",
      },
      {
        id: "v-khalid-1",
        patientId: "p-khalid",
        date: "9 Jun 2025",
        diagnosis: "Acute bronchitis",
        treatment: "Azithromycin 250mg OD x 5 days, inhaler PRN",
        notes: "Cough productive, mild wheeze. Acute infection follow-up protocol started.",
      },
      {
        id: "v-mariam-1",
        patientId: "p-mariam",
        date: "28 May 2025",
        diagnosis: "Dental extraction (wisdom tooth)",
        treatment: "Extraction under local anaesthesia, analgesia, salt-water rinses",
        notes: "Recovery uneventful. Post-procedure protocol completed.",
      },
      {
        id: "v-yusuf-1",
        patientId: "p-yusuf",
        date: "30 May 2025",
        diagnosis: "Type 2 diabetes mellitus",
        treatment: "Metformin 1g BID, dietary counselling",
        notes: "Chronic condition monitoring protocol active.",
      },
      {
        id: "v-reem-1",
        patientId: "p-reem",
        date: "5 Jun 2025",
        diagnosis: "Asthma, stable",
        treatment: "Salbutamol inhaler PRN, preventer continued",
        notes: "Well controlled. Chronic condition monitoring protocol active.",
      },
    ],
    patientProtocols: [
      { id: "pp-aisha", patientId: "p-aisha", protocolId: "post-procedure", startDate: "10 Jun 2025", status: "active", nextCheckin: "Day 3 · 13 Jun" },
      { id: "pp-omar", patientId: "p-omar", protocolId: "acute-infection", startDate: "8 Jun 2025", status: "active", nextCheckin: "Day 5 · 13 Jun" },
      { id: "pp-fatima", patientId: "p-fatima", protocolId: "chronic-condition", startDate: "2 Jun 2025", status: "active", nextCheckin: "Week 2 · 16 Jun" },
      { id: "pp-khalid", patientId: "p-khalid", protocolId: "acute-infection", startDate: "9 Jun 2025", status: "active", nextCheckin: "Day 5 · 14 Jun" },
      { id: "pp-mariam", patientId: "p-mariam", protocolId: "post-procedure", startDate: "28 May 2025", status: "completed", nextCheckin: "Completed" },
      { id: "pp-yusuf", patientId: "p-yusuf", protocolId: "chronic-condition", startDate: "30 May 2025", status: "active", nextCheckin: "Week 2 · 13 Jun" },
      { id: "pp-reem", patientId: "p-reem", protocolId: "chronic-condition", startDate: "5 Jun 2025", status: "active", nextCheckin: "Week 1 · 12 Jun" },
    ],
    checkins: [
      {
        id: "c-aisha-1",
        patientId: "p-aisha",
        protocolId: "post-procedure",
        message: "Day 1 check-in: How are you feeling today? Any pain, swelling, bleeding, or fever?",
        response: "A little sore but doing well. No fever or bleeding.",
        severity: "LOW",
        matchedRules: [],
        summary: "Day 1 post-procedure check-in. Patient reports mild soreness, no red flags. Continue routine monitoring.",
        symptoms: ["mild soreness"],
        createdAt: "11 Jun 2025",
      },
      {
        id: "c-omar-1",
        patientId: "p-omar",
        protocolId: "acute-infection",
        message: "Day 2 check-in: How are you feeling? Any fever, cough, or breathing difficulty?",
        response: "Still coughing and not improving much. No fever.",
        severity: "MEDIUM",
        matchedRules: ["NOT_IMPROVING"],
        summary: "Day 2 acute-infection check-in. Cough persists with no improvement so far; no fever reported. Nurse review recommended.",
        symptoms: ["persistent cough", "no improvement"],
        createdAt: "11 Jun 2025",
      },
      {
        id: "c-khalid-1",
        patientId: "p-khalid",
        protocolId: "acute-infection",
        message: "Day 2 check-in: How are you feeling? Any fever, cough, or breathing difficulty?",
        response: "My cough is getting worse and I have difficulty breathing at night.",
        severity: "HIGH",
        matchedRules: ["BREATHING_DIFFICULTY", "WORSENING_SYMPTOMS"],
        summary: "Day 2 acute-infection check-in. Worsening cough with reported breathing difficulty. Red flags detected; escalated to doctor.",
        symptoms: ["worsening cough", "difficulty breathing"],
        createdAt: "11 Jun 2025",
      },
      {
        id: "c-yusuf-1",
        patientId: "p-yusuf",
        protocolId: "chronic-condition",
        message: "Week 1 check-in: How are your readings and medication routine?",
        response: "I forgot to take my medication two days this week.",
        severity: "MEDIUM",
        matchedRules: ["MISSED_MEDICATION"],
        summary: "Week 1 chronic-condition check-in. Patient reports missed medication doses. Nurse follow-up advised.",
        symptoms: ["missed medication"],
        createdAt: "6 Jun 2025",
      },
    ],
    alerts: [
      {
        id: "a-omar-1",
        patientId: "p-omar",
        checkinId: "c-omar-1",
        severity: "MEDIUM",
        assignedRole: "NURSE",
        reason: "Non-urgent findings: No improvement.",
        status: "active",
        summary: "Cough persists with no improvement so far; no fever reported. Nurse review recommended.",
        message: "Still coughing and not improving much. No fever.",
        matchedRules: ["NOT_IMPROVING"],
        createdAt: "11 Jun 2025",
      },
      {
        id: "a-khalid-1",
        patientId: "p-khalid",
        checkinId: "c-khalid-1",
        severity: "HIGH",
        assignedRole: "DOCTOR",
        reason: "Red flags detected: Breathing difficulty, Worsening symptoms.",
        status: "active",
        summary: "Worsening cough with reported breathing difficulty at night. Escalated to doctor for review.",
        message: "My cough is getting worse and I have difficulty breathing at night.",
        matchedRules: ["BREATHING_DIFFICULTY", "WORSENING_SYMPTOMS"],
        createdAt: "11 Jun 2025",
      },
      {
        id: "a-yusuf-1",
        patientId: "p-yusuf",
        checkinId: "c-yusuf-1",
        severity: "MEDIUM",
        assignedRole: "NURSE",
        reason: "Non-urgent findings: Missed medication.",
        status: "follow_up_sent",
        summary: "Patient reports missed medication doses this week. Follow-up message sent; awaiting adherence update.",
        message: "I forgot to take my medication two days this week.",
        matchedRules: ["MISSED_MEDICATION"],
        createdAt: "6 Jun 2025",
      },
    ],
    appointments: [],
  };
}
